#!/usr/bin/env bash
# Sets up an nginx web serve
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '/server_name _.*/a \\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default 
sudo service nginx restart
