#!/usr/bin/env bash
# Installing and starting nginx and configuring redirection
sudo apt-get install nginx -y
sed -i "15i\add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
