#!/usr/bin/env bash
# display Best School 10 times and hi in line 10.
i=1
while [ $i -lt 10 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
	done
