#!/usr/bin/env bash
# gives information about school file.
FILE="school"
if [ -e "$FILE" ]
then
	echo "$FILE exists"
	
	if [ -s "$FILE" ]
	then
		echo "$FILE file is empty"
	else
		echo "$FILE file is not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "$FILE is a regular file"
	fi 
else
	echo "$FILE does not exist"
fi
